### ISSUE TITLE
Anonymizer for function names

### ISSUE THREAD

**Issue by cjuhlin** [codekuu/pyprojectviz#10]
### Summary
 It would be nice to have a feature that anonymizes the names of functions within the generated images. This allows for the sharing of images without disclosing too much detailed information.

**Comment by codekuu** [comment]
Great idea! Will add this

**Comment by codekuu** [comment]
@cjuhlin opened does this fill your needs?: https://github.com/codekuu/pyprojectviz/pull/11

**Comment by cjuhlin** [comment]
> @cjuhlin opened does this fill your needs?: #11

LGFM!

**Comment by codekuu** [comment]
Done, closing!
